from_latest_tag = true
ignore_merge_commits = true
tag_prefix = "v"
branch_whitelist = ["main"]

pre_bump_hooks = [
    "cargo test",
    "cargo clippy -- -D warnings",
    "cargo fmt -- --check",
    "cargo set-version {{version}}",
]

post_bump_hooks = []

[commit_types]
chore = { omit_from_changelog = true }
test = { omit_from_changelog = true }
ci = { omit_from_changelog = true }
style = { omit_from_changelog = true }

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
repository = "cargo-dupes"
owner = "mpecan"
authors = [
    { signature = "Matjaz Domen Pecan", username = "mpecan" },
]
