from_latest_tag = true
ignore_merge_commits = true
tag_prefix = "v"
branch_whitelist = ["main"]

[commit_types]
chore = { omit_from_changelog = true }
test = { omit_from_changelog = true }
ci = { omit_from_changelog = true }
style = { omit_from_changelog = true }
